site_name: Human Phenotype Ontology Internationalisation Effort
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

nav:
  - About HPO translations: index.md
  - How to submit a language profile: submit.md
  - Contact: contact.md
repo_url: https://github.com/obophenotype/hpo-translations/
site_url: https://obophenotype.github.io/hpo-translations/
edit_uri: docs/
